### ISSUE TITLE
Commands not Working

### ISSUE THREAD

**Issue by wumbly12** [NathanCollaert/LiteDeathBan#1]
Hey there,
I love the idea of your plugin, however none of the commands appear to be working. I'm on craftbukkit 1.14.4 and get the message "An internal error occurred while attempting to perform this command" whenever I try to do anything such as /revive , /setlives , etc.

The ban system is working perfectly and I would love to use this plugin with my friends.

**Comment by NathanCollaert** [comment]
Hey wumbly12,
Currently the latest version of LiteDeathBan (1.1.0) is only compatible with Spigot. I use certain Spigot methods in the plugin which CraftBukkit doesn't have.
I might change the code in the future to also work with CraftBukkit, depending on how big of a change it is.

Greetings, Nathan

**Comment by wumbly12** [comment]
Ah okay, thanks for the response.
