### ISSUE TITLE
Multiworld issue

### ISSUE THREAD

**Issue by Ragemalik** [NathanCollaert/LiteDeathBan#3]
in my survival server i wanted one of my world to be hardcore but there was a bug and it did not allow me to get banned from the server after it reached to my life limit i have done everything correct in the files to perform this action because i had a professional to help me i would love you to fix this issue (on1.14.4) as this will make my server amazing!!!!!! your plugin only allows it to not be config and if you do config it it will not function properly

**Comment by NathanCollaert** [comment]
Hey there, I don't know if you're still using my plugin but I'd like to help you out.
I did not get a notification for this issue so that's why my response is this late.
As I'm understanding this correctly you set up the plugin to disable everything on every world except for one. When dying with 1 life remaining you didn't get banned?

**Comment by Ragemalik** [comment]
Respond to your email I did not get banned and with my expert he said it was a bug so I did not get banned my expert was from apex hosting

You’re sensory Rehan malik

On 28 Nov 2019, at 3:16 pm, Nathan <notifications@github.com> wrote:

﻿

Hey there, I don't know if you're still using my plugin but I'd like to help you out.
I did not get a notification for this issue so that's why my response is this late.
As I'm understanding this correctly you set up the plugin to disable everything on every world except for one. When dying with 1 life remaining you didn't get banned?

**Comment by NathanCollaert** [comment]
Hey ragemalik,
I tried to recreate this bug but unfortunately I couldn't. Are you sure you weren't OP on the server since they get all the bypass permissions by default.
I would love to help you out here but everything seems to work on my end.

**Comment by Ragemalik** [comment]
Replying to your comment I’m using multiverse and so I disabled it on every world except form one but when I die I don’t get banned

You’re sensory Rehan malik

On 28 Nov 2019, at 3:16 pm, Nathan <notifications@github.com> wrote:

﻿

Hey there, I don't know if you're still using my plugin but I'd like to help you out.
I did not get a notification for this issue so that's why my response is this late.
As I'm understanding this correctly you set up the plugin to disable everything on every world except for one. When dying with 1 life remaining you didn't get banned?

**Comment by NathanCollaert** [comment]
I tried running multiple worlds with Multiverse-core and disabled all of them except for one.
Everything was working as expected, I got banned when I died on the enabled world, I did not lose lives/get banned on worlds that were disabled.
Are you sure you are running the latest version?
Are you sure you're not having the bypass permissions / have OP?
Are you sure you didn't disable the world by accident?

I really can't, for the life of me, recreate this bug.

**Comment by Ragemalik** [comment]
I have op on my server is that why and can you tel me how to do it just in case I did it wrong

You’re sensory Rehan malik

On 1 Dec 2019, at 1:39 pm, Nathan <notifications@github.com> wrote:

﻿

I tried running multiple worlds with Multiverse-core and disabled all of them except for one.
Everything was working as expected, I got banned when I died on the enabled world, I did not lose lives/get banned on worlds that were disabled.
Are you sure you are running the latest version?
Are you sure you're not having the bypass permissions / have OP?
Are you sure you didn't disable the world by accident?

I really can't, for the life of me, recreate this bug.

**Comment by NathanCollaert** [comment]
OP's have all permissions by default. LiteDeathBan has bypass permissions that allows users with these permissions to not lose lives/get banned. Since you're an OP on your server, you'll also have these permissions. Normal players (the ones without OP) will lose lives/get banned normally.

**Comment by Ragemalik** [comment]
Sorry for this issue I put and thank you for your solution

Your sincerely,

Rehan Malik

On 1 Dec 2019, at 4:10 pm, Nathan <notifications@github.com> wrote:

﻿

OP's have all permissions by default. LiteDeathBan has bypass permissions that allows users with these permissions to not lose lives/get banned. Since you're an OP on your server, you'll also have these permissions. Normal players (the ones without OP) will lose lives/get banned normally.
